reload/ddsdk2016

composer.json
Date-fields are all in UTC, but when indexing them search_api_solr
parsed a formatted version of the date without a timezone specified
causing php to assume the timestamp was in UTC+1 and indexing a wrongly
corrected timestamp (now effectivly UTC-1)
DDSDK-361
=> Patch search_api_solr with to fix bug in date handling

composer.json
By default the composer-patches will print out a message if a patch does not apply but the process continues. We want the process to fail entirely to ensure that patch failures hare handled properly.
The other option would be to rely on the COMPOSER_EXIT_ON_PATCH_FAILURE environment variable but we want to ensure that this happens across environments.
=> Make composer fail if patches do not apply

composer.json, composer.lock
For this to work we need a recent version of the composer-patches 
package.
See  https://www.previousnext.com.au/blog/patch-drupal-core-without-things-ending-up-corecore-or-coreb
A number of other pending changes to the lock file was also added.
=>  Default to p2 patch level for Drupal Core

composer.json
I am choosing to patch core, as we're running an old 8.4.8 version,
and Drupal security is suggesting to update to 8.5.x
=> DDSDK-418 SA-CORE-2018-006

configuration/drupal/field.storage.node.field_badge_type.yml, configuration/drupal/views.view.badges.yml
Added new badge type "other" ("Øvrige mærker") to the badge node type.
The badge type is also added as exposed filter value on the `/maerker` view.
See DDSDK-420.
=> Add new badge type "other"

composer.json, composer.lock, configuration/drupal/core.extension.yml, configuration/drupal/forward.settings.yml, configuration/drupal/language.content_settings.node.article.yml, configuration/drupal/language.content_settings.node.event.yml, configuration/drupal/language/da/views.view.jobpostings.yml, configuration/drupal/monitoring.sensor_config.core_requirements_scheduler.yml, configuration/drupal/mungo.settings.yml, configuration/drupal/node.type.article.yml, configuration/drupal/node.type.badge.yml, configuration/drupal/node.type.event.yml, configuration/drupal/node.type.section_page.yml, configuration/drupal/scheduler.settings.yml, configuration/drupal/views.view.jobpostings.yml, configuration/drupal/views.view.scheduler_scheduled_content.yml, web/modules/custom/dds_jobposting/dds_jobposting.info.yml, web/modules/custom/dds_jobposting/dds_jobposting.module, web/modules/custom/dds_jobposting/dds_jobposting.routing.yml, web/modules/custom/dds_jobposting/src/Controller/JobPostingController.php, web/modules/custom/dds_jobposting/templates/dds-jobposting.html.twig, web/modules/custom/dds_update/dds_update.install, web/themes/custom/mungo/assets_src/sass/layout/deck.scss, web/themes/custom/mungo/assets_src/sass/layout/view-page.scss, web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss, web/themes/custom/mungo/theme-settings.php
This PR introduces a module that serves up a job-listings page on /jobs
The page is rendered via a custom controller, and the page itself consits of two views that displays articles tagged with specific job-related tags.
The top-image used on the page is configurable via theme settings, and we default using the badge-topimage as
it is already present.
DDSDK-426
=> Add a joblistings section.

docker-compose.yml, scripts/docker/docker-reset.sh
drupal-apache-fpm now has https support and the abillity to generate
certificates. So, we drop hitch, and instead rely on either drupal-apache-fpm
or a nginx-proxy based solution.
We also do away with links as they are deprecated.
=> Switch to using drupal-apache-fpm and or a proxy for https

docker-compose.yml
* Simplify mkcert setup
* Make it non-obstrusive for linux users
* Make it consistent with updated guide on https://github.com/reload/docker-drupal-apache-fpm
=> Simplify mkcert setup

web/modules/custom/dds_link/dds_link.services.yml, web/modules/custom/dds_link/src/EventSubscriber/DownloadRedirectSubscriber.php
When linking to download nodes we don't want to go to the node view page and click the file link. We want to go directly to downloading the file.
See DDSDK-433.
=> Add redirect of download node types to field_file URL

web/modules/custom/dds_link/dds_link.module, web/modules/custom/dds_link/src/EventSubscriber/DownloadRedirectSubscriber.php, web/themes/custom/mungo/mungo.theme
Test by creating and editing a download node.
After submit it should redirect back to the edit form.
Page view of a download node should still redirect to the file (if one exists only, though).
=> Hardening and redirect on edit submit

web/themes/custom/mungo/assets_src/sass/components/download.scss, web/themes/custom/mungo/templates/content/node--download--list-teaser.html.twig, web/themes/custom/mungo/templates/content/node--download--teaser.html.twig
versus
Se det i real life på fx https://pr-323-mn4kqoi-55isd6w54kg6s.eu.platform.sh/artikel/korpsledelsen
See DDSDK-310.
=> Add styling to download link to align with "send mail" link

.platform.app.yaml
* Run drush cron with `--uri` option
Use Platform CLI to get primary URL.
* Only run cron every 5 minutes
Platform.sh won't schedule it more frequently than that anyway.
* Don't hardcode document root
=> Tweak drush cron

.platform.app.yaml, .platform/services.yaml, composer.json, composer.lock, configuration/drupal/core.extension.yml, docker-compose.yml, web/sites/default/docker.settings.php, web/sites/default/platformsh.common.settings.php
After deploy Drupal will use Redis as cache backend.
To free up space in the cache tables in the database you'll manually have to run:
```sql
TRUNCATE cache_bootstrap;
TRUNCATE cache_config;
TRUNCATE cache_container;
TRUNCATE cache_data;
TRUNCATE cache_default;
TRUNCATE cache_discovery;
TRUNCATE cache_dynamic_page_cache;
TRUNCATE cache_entity;
TRUNCATE cache_menu;
TRUNCATE cache_page;
TRUNCATE cache_render;
TRUNCATE cache_rest;
TRUNCATE cache_toolbar;
```
This PR also removes the periodic `drush cache:rebuild`.
=> Add redis cache as cache backend for Drupal

.platform.app.yaml
DDSDK-448
Mitigates SA-CORE-2019-009 by blocking access to web/install.php and web/core/install.php
.platform.app.yaml
DDSDK-448
=> Block access to install.php to mitigate SA-CORE-2019-009

.github/workflows/github-security-jira.yml
Secrets has been added in GitHub settings.
See DDSDK-451.
=> Extend security monitoring to monitor GitHub Security Alerts

composer.json, composer.lock
Updates pathauto to 8.x-1.6.
To fix the actual problem in DDSDK-457 we are better off upgrading core. To upgrade core we need to upgrade to a newer pathauto before doing the core upgrade.
Only `composer.{json|lock}` changes, so start there :)
Creating an updating i.e. articles and noticing the URLs.
n/a
DDSDK-457.
n/a
n/a
=> Update pathauto to 8.x-1.6 in preparation of core update

.codeclimate.yml
The existing config for Code Climate was old and there was no builds on Code Climate. Let's try to update the config to a newer version (2) to see if we'll get builds back.
=> Update Code Climate config

composer.lock, configuration/drupal/redirect.settings.yml
There is an issue, where index.php 'randomly' appears in
some urls. An example:
https://dds.dk/index.php/artikel/nye-spejderchefer-vi-skal-skabe-modige-born-og-unge
It's not all pages, and there is not a clear pattern why
it happens sometimes. The 'real' path is valid, but the
issue appears when links on the website actually links
to the index.php versions.
It appears to be an obscure bug in D8 when using
platform.sh and sitemap/pathauto/others(?)
This commit implements a quickfix, described here:
https://www.drupal.org/project/drupal/issues/3050261
'Just a quick note to let folks know that we installed the
Redirect module and enabled Enforce clean and canonical URLs,
and haven't had the problem return since (it's been weeks).'
It appears to work for DDS too.
-------
Someone has made …
=> Fix issues with index.php in URLs. DDSDK-479

.github/workflows/phpstan.yml, phpstan.neon, web/modules/custom/dds_search/src/Plugin/Block/SearchFormBlock.php
Tweaks phpstan configuration.
Fixes finding from phpstan:
```
------ ----------------------------------------------------------------------------------
Line   modules/custom/dds_search/src/Plugin/Block/SearchFormBlock.php
------ ----------------------------------------------------------------------------------
42     Unsafe usage of new static().
💡 See: https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static
------ ----------------------------------------------------------------------------------
```
n/a
n/a
n/a
n/a
n/a
n/a
=> Tweak phpstan setup in GitHub Actions

.platform.app.yaml
The Platform.sh plan was increased with 5 GiB. This gives us 2 Gib unallocated disk for later if i.e. the database or solr runs short.
I have mailed Nikolas and Camilla so they can adjust the invoices etc.
n/a
n/a
n/a
n/a
n/a
n/a
=> Increase persistent disk with 3 GiB

composer.json, composer.lock, configuration/drupal/core.extension.yml, configuration/drupal/monitoring.sensor_config.core_requirements_raven.yml, configuration/drupal/raven.settings.yml, web/sites/default/platformsh.env.master.settings.php
---
On some of our other sites, we're using Sentry to detect PHP and Javascript errors.
It's working really well on Balder, and seeing as I just upgraded this site to Drupal 9, I'd feel a bit safer, knowing that if the log is suddenly filled with errors, we'll see it *somewhere*.
You can see the dashboard here:
https://sentry.io/organizations/reload-3j/issues/?project=5908277&query=is%3Aresolved&statsPeriod=14d
I tested it locally. I've disabled that now, so now it'll only be errors from the master environment that will show up.
=> Thats so raven

web/modules/custom/dds_tracking/dds_tracking.module
We do exactly the same on Balder:
https://github.com/reload/balder/blob/master/web/modules/custom/balder_tracking/balder_tracking.module#L16
I've obviously updated the embed code to match what DDS have written in DDSDK-542
=> GDPR-compliant FB Pixel tracking. BALDER-542

configuration/drupal/core.entity_view_display.node.article.default.yml, configuration/drupal/core.entity_view_display.node.article.teaser.yml, configuration/drupal/facets.facet.activity_type.yml, configuration/drupal/facets.facet.area.yml, configuration/drupal/facets.facet.badge_target_group.yml, configuration/drupal/facets.facet.content_type.yml, configuration/drupal/facets.facet.duration.yml, configuration/drupal/facets.facet.event_type.yml, configuration/drupal/facets.facet.target_group.yml, configuration/drupal/facets.facet.target_group_taxonomy_term_name.yml, configuration/drupal/facets.facet.topic_taxonomy_term_name.yml, configuration/drupal/views.view.search.yml
1. `drush cex` before my changes that seems to be missing
1. Add the "Målgruppe" vocabulary as a new facet to the search view. I've placed it under "Emne" but over "Indholdstype" in the search page, which I think makes the most sense. Let me know what you think 🙂 
Commit by commit and try and use the search and see if it works as expected.
DG-268
=> DG-268: Add 'Målgruppe' vocab as a facet

web/themes/custom/mungo/assets_src/sass/track/_base.scss, web/themes/custom/mungo/templates/content/node--teaser.html.twig
Show topic in activity teaser
In below screenshots, it's the "BANG" teaser that is an activity
In dds context: 
In track context: 
SPJ-150
=> SPJ-150: Show topic in activity teaser

web/themes/custom/mungo/assets_src/sass/track/_section-page.scss, web/themes/custom/mungo/templates/track/track-section-page--header.html.twig
- Don't target on the image view_mode
This makes sure that the image is always "pushed" down correctly on a track page.
- Adjust the track-stars and show them with the correct bg color
Also make sure we style the track-frontpage star correctly.
=> misc fixes for track

.platform.app.yaml, .platform/services.yaml
Adjust allocations to be divisible by 1024.
Current usages:
```console
$ platform db:size -e master
Checking database service mysqldb...
+----------------+-----------------+--------+
| Allocated disk | Estimated usage | % used |
+----------------+-----------------+--------+
| 2.1 GiB        | 1022.2 MiB      | ~ 47%  |
+----------------+-----------------+--------+
Warning
This is an estimate of the database's disk usage. It does not represent its real size on disk.
$ platform mount:size -e master
Checking disk usage for all mounts on 55isd6w54kg6s-master-7rqtwti--drupal@ssh.eu.platform.sh...
+-------------------------+----------+----------+----------+-----------+--------+
| Mount(s)                | Size(s)  | Disk     | Used     | Available | % Used | …
```
=> Increase disk usage

configuration/drupal/search_api.index.nodes.yml, docker-compose.yml
Make the npm container work for me, and fix the search.
The boost for most content types was set to 0, but boosts are multiplied together, so 0 works as a kill-switch that sets boost to 0 no matter the value of other boosts. This PR sets them to 1 (which is also the default) instead.
DDSDK-562
Before:
And after:
=> Dds 562 search

configuration/drupal/core.entity_form_display.paragraph.video.default.yml, configuration/drupal/core.entity_view_display.paragraph.video.default.yml, configuration/drupal/core.entity_view_display.paragraph.video.search_index.yml, configuration/drupal/field.field.paragraph.video.field_content_topic.yml, configuration/drupal/field.storage.paragraph.field_content_topic.yml, web/themes/custom/mungo/assets_src/sass/drupal/video_embed_field.scss, web/themes/custom/mungo/assets_src/sass/tools/_colors.scss, web/themes/custom/mungo/templates/layout/paragraph--deck.html.twig, web/themes/custom/mungo/templates/paragraphs/paragraph--video.html.twig
- Added field for video topic on video embeds
- Added change to paragraph--deck template, since it was casuing extra padding even tho empty
This PR adds a field for adding a video topic for the new video embed template. 
This pr also suggests a change to the paragraph-deck template, since it is added the padding of the element, even tho there is no content in the element. 
Test that you can change the topic / caption for a video. And that responsiveness is alright. 
https://reload.atlassian.net/jira/software/c/projects/DDSDK/boards/478?modal=detail&selectedIssue=DDSDK-597
I used aspect ratio CCS for the container of the iframe, that is positioned absolute. Thoughts?
Do i need a fallback?
=> DDSDK 597 video modul

configuration/drupal/core.entity_form_display.paragraph.content_link.default.yml, configuration/drupal/core.entity_view_display.paragraph.content_link.default.yml, configuration/drupal/core.entity_view_display.paragraph.content_link.search_index.yml, configuration/drupal/field.field.paragraph.content_link.field_content_link_lead.yml, configuration/drupal/field.field.paragraph.content_link.field_show_as_button.yml, configuration/drupal/field.storage.paragraph.field_show_as_button.yml, web/themes/custom/mungo/assets_src/sass/components/content-link.scss, web/themes/custom/mungo/mungo.theme, web/themes/custom/mungo/templates/paragraphs/paragraph--content-link.html.twig
Added a checkbox to enable button styling on the content-link paragraph.
Se den nye variation af content-link: https://pr-442-7oikaoy-55isd6w54kg6s.eu.platform.sh/artikel/logoer-0
https://reload.atlassian.net/browse/DDSDK-621
=> Added optional button styling to content-link - DDSDK-621

.platform.app.yaml, .platform/services.yaml
Database-disken er faretruende tæt på at være fyldt (den har faktisk været det og sitet kun reddet af cache).
Vi flytter lige en enkelt GiB fra disk til DB så den kan holde sig i live.
Disk har stadig plads til dette, men skal nok også udvides inden længe, men så kan vi nå at vende det med kunden når de er på kontoret igen (grundlovsdag..).
=> Reallocate 1 GiB from disk to db

composer.json, composer.lock, configuration/drupal/core.extension.yml, configuration/drupal/plausible_tracking.settings.yml, web/sites/default/platformsh.env.master.settings.php, web/themes/custom/mungo/mungo.theme
For DDS.dk: 
Removes the old plausbile script, and adds a new using the plausible_tracking module. 
This can be tested on plausible ddsdk.docker. 
Only the search part is implemented, the filtering part is not. 
Blivspejder.dk has had their script adjusted manually, just wanted to note that here since it's a part of the ticket. 
[DDSDK-625](https://reload.atlassian.net/browse/DDSDK-625)
[DDSDK-625]: https://reload.atlassian.net/browse/DDSDK-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added plausible module for DDSDK

web/sites/default/docker.settings.php, web/sites/default/platformsh.env.master.settings.php
Blocks dds' own IP from plausible. 
Changes the local plausible path to work with the plausible tracking module
https://reload.atlassian.net/jira/software/c/projects/DDSDK/boards/478?modal=detail&selectedIssue=DDSDK-625
=> blocked dds IP from plausible on prod and changed local settings

web/sites/default/common.settings.php, web/sites/default/platformsh.env.master.settings.php, web/themes/custom/mungo/assets_src/sass/components/_facebook.scss, web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss, web/themes/custom/mungo/mungo.theme, web/themes/custom/mungo/templates/content/node--activity--full.html.twig, web/themes/custom/mungo/templates/content/node--article--full.html.twig
Removes everything concerning facebook comments for DDS.dk
Old PRs for adding facebook comments:
Not saying this is **not**. all,  was just to get an idea if relevant. 
- https://github.com/search?q=repo%3Areload%2Fddsdk2016+facebook+&type=commits
See prod /artikel/plej-jeres-lederfaellesskab
and local /artikel/plej-jeres-lederfaellesskab
I left lost pixel failing so u can see the changes there too / instead. 
The comment thread should not be appearing /be loaded in (iframe) 
Is there something i have not considered to delete ?
=> Removed facebook comments from DDSDK

web/themes/custom/mungo/mungo.theme
The information regarding the settings of the popup can be found in the campaign on sleeknote. Login can be found in LP.
DDSDK-676
DDSDK-674
This PR adds a sleeknote popup to the dds.dk. Specfifically 3 URL's : 
- https://dds.dk/artikel/kan-jeg-blive-spejder-som-voksen
- https://dds.dk/nyleder
- https://dds.dk/rollen-som-spejderleder
As the described in Jira, the popup is supposed to trigger on referral from google. 
For simplicity, i've made it so it current is activated after 3s and scroll of page. It's complicated to test that locally, so i'll do this afterwards. 
For now just test that it works on the 3 mentioned URLs, and not on other pages. 
The campaign is looking at only dds.dk domain (I can't find a reasonable way to add a testing domain in sleeknote). I came around this by …
=> Add sleeknote popup for dds.dk

configuration/drupal/core.entity_form_display.paragraph.generic_link_card.default.yml, configuration/drupal/core.entity_view_display.paragraph.generic_link_card.default.yml, configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col1.yml, configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col2.yml, configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col1.yml, configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col2.yml, configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col3.yml, configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col1.yml, configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col2.yml, configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col3.yml, configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col4.yml, configuration/drupal/field.field.paragraph.generic_link_card.field_generic_link_card_link.yml, configuration/drupal/field.field.paragraph.generic_link_card.field_generic_link_card_title.yml, configuration/drupal/field.field.paragraph.generic_link_card.field_generic_link_desc.yml, configuration/drupal/field.storage.paragraph.field_generic_link_card_link.yml, configuration/drupal/field.storage.paragraph.field_generic_link_card_title.yml, configuration/drupal/field.storage.paragraph.field_generic_link_desc.yml, configuration/drupal/paragraphs.paragraphs_type.generic_link_card.yml, web/modules/custom/dds_track/dds_track.module, web/themes/custom/mungo/assets_src/sass/components/_block-form-search.scss, web/themes/custom/mungo/assets_src/sass/components/_generic-link-card.scss, web/themes/custom/mungo/assets_src/sass/mixins/_typography.mixins.scss, web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss, web/themes/custom/mungo/assets_src/sass/tools/_colors.scss, web/themes/custom/mungo/assets_src/sass/tools/_variables.scss, web/themes/custom/mungo/assets_src/sass/track/_track-tools.bundle.scss, web/themes/custom/mungo/assets_src/sass/track/_track.bundle.scss, web/themes/custom/mungo/templates/paragraphs/paragraph--generic-link-card.html.twig
A basic paragraph that display link cards. Each card has a title and a description. If the link is external an icon is displayed next to the title. If the link points to a track node then it'll get track styling. This is done in a preprocess using a track module helper function that determines if node is track universe.
Enabled the paragraph for column deck 4 and 3 but not for deck 2 since it's broken at the moment. I've created a ticket on it: DDSDK-761.
**Paragraph in 4 and 3 columns**
------------------------------------------------
**Other changes:**
**Fix undefined css track variables**
I had to change the load order of css to ensure that track tools load before components so we have access to variables and mixins. I still load the main track bundle (css for components) after all …
=> Add generic link card paragraph - DDSDK-737
