reload/ddsdk2016

.scrutinizer.yml
composer.json
composer.lock
tests/.gitignore
tests/phpunit.xml.dist

Scrutinizer setup

---

configuration/drupal/block.block.mungo_account_menu.yml
configuration/drupal/block.block.mungo_branding.yml
configuration/drupal/block.block.mungo_footer.yml
configuration/drupal/block.block.mungo_help.yml
configuration/drupal/block.block.mungo_local_actions.yml
configuration/drupal/block.block.mungo_local_tasks.yml
configuration/drupal/block.block.mungo_main_menu.yml
configuration/drupal/block.block.mungo_page_title.yml
configuration/drupal/block.block.mungo_powered.yml
configuration/drupal/block.block.mungo_search.yml
configuration/drupal/block.block.topmenu.yml

Adding missing configuration

---

.platform.app.yaml
gulpfile.js
scripts/docker/docker-reset.sh

Adding gulp build and having platform use it

---

theme_assets/mungo/javascript/base.js
theme_assets/mungo/sass/layout/header.scss

Fix logo position

---

theme_assets/mungo/sass/components/menu.scss
theme_assets/mungo/sass/layout/header.scss
web/themes/custom/mungo/templates/navigation/menu--footer-social.html.twig
web/themes/custom/mungo/templates/navigation/menu--footer.html.twig
web/themes/custom/mungo/templates/navigation/menu--main.html.twig
web/themes/custom/mungo/templates/navigation/menu--top-menu.html.twig

Cleanup menu

---

theme_assets/mungo/sass/layout/footer.scss

Fix footer with trees

---

theme_assets/mungo/javascript/typekit.js
theme_assets/mungo/sass/_variables.scss
theme_assets/mungo/sass/base/typography.scss
theme_assets/mungo/sass/components/menu.scss
theme_assets/mungo/sass/layout/header.scss
web/themes/custom/mungo/mungo.info.yml
web/themes/custom/mungo/mungo.libraries.yml
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/block/block--search-form-block.html.twig
web/themes/custom/mungo/templates/block/block--system-menu-block--footer-social.html.twig
web/themes/custom/mungo/templates/navigation/menu--footer.html.twig
web/themes/custom/mungo/templates/navigation/menu--main.html.twig

Use Proxima Nova from TypeKit and adjust header and footer.

---

theme_assets/mungo/sass/components/menu.scss
theme_assets/mungo/sass/layout/footer.scss
web/themes/custom/mungo/templates/navigation/menu--footer.html.twig

Fix up footer menu

---

composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/stage_file_proxy.settings.yml
docker/docker.settings.php

Add stage_file_proxy - point it at develop

---

configuration/drupal/core.entity_view_display.media.image.default.yml
configuration/drupal/user.role.anonymous.yml
theme_assets/mungo/sass/_colors.scss
theme_assets/mungo/sass/base/typography.scss
theme_assets/mungo/sass/bootstrap.custom.scss
theme_assets/mungo/sass/components/main-media.scss
theme_assets/mungo/sass/layout/header.scss
web/themes/custom/mungo/templates/content/node--article--full.html.twig
web/themes/custom/mungo/templates/field/field--media--field-byline--image.html.twig
web/themes/custom/mungo/templates/layout/page.html.twig

Theming article

---

configuration/drupal/core.entity_form_display.paragraph.factbox.default.yml
configuration/drupal/core.entity_view_display.paragraph.factbox.default.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.paragraph.factbox.field_factbox_text.yml
configuration/drupal/field.storage.paragraph.field_factbox_text.yml
configuration/drupal/paragraphs.paragraphs_type.factbox.yml
theme_assets/mungo/sass/_colors.scss
theme_assets/mungo/sass/base/typography.scss
theme_assets/mungo/sass/components/factbox.scss
theme_assets/mungo/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme

Factbox paragraph

---

configuration/drupal/core.entity_form_display.paragraph.video.default.yml
configuration/drupal/core.entity_view_display.paragraph.video.default.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.paragraph.video.field_video.yml
configuration/drupal/field.field.paragraph.video.field_video_caption.yml
configuration/drupal/field.storage.paragraph.field_video.yml
configuration/drupal/field.storage.paragraph.field_video_caption.yml
configuration/drupal/paragraphs.paragraphs_type.video.yml
theme_assets/mungo/sass/base/media.scss
theme_assets/mungo/sass/base/typography.scss
theme_assets/mungo/sass/components/main-media.scss
theme_assets/mungo/sass/components/video.scss
theme_assets/mungo/sass/mixins/typography.mixins.scss
theme_assets/mungo/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme

Video paragraph

---

web/themes/custom/mungo/assets_src/sass/layout/header.scss
web/themes/custom/mungo/assets_src/sass/mixins/breakpoints.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss

Introduce breakpoints

---

configuration/drupal/core.entity_form_display.paragraph.content_link.default.yml
configuration/drupal/core.entity_view_display.paragraph.content_link.default.yml
configuration/drupal/core.extension.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.paragraph.content_link.field_content_link.yml
configuration/drupal/field.field.paragraph.content_link.field_content_link_lead.yml
configuration/drupal/field.field.paragraph.content_link.field_show_thumbnail.yml
configuration/drupal/field.storage.paragraph.field_content_link.yml
configuration/drupal/field.storage.paragraph.field_content_link_lead.yml
configuration/drupal/field.storage.paragraph.field_show_thumbnail.yml
configuration/drupal/image.style.thumbnail_4_3.yml
configuration/drupal/paragraphs.paragraphs_type.content_link.yml
web/modules/custom/dds_content_link/dds_content_link.info.yml
web/modules/custom/dds_content_link/dds_content_link.module
web/themes/custom/mungo/assets_src/sass/_colors.scss
web/themes/custom/mungo/assets_src/sass/components/content-link.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/paragraphs/paragraph--content-link.html.twig

The content-link paragraph type

---

configuration/drupal/core.entity_form_display.paragraph.quotation.default.yml
configuration/drupal/core.entity_view_display.paragraph.quotation.default.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.paragraph.quotation.field_quotation.yml
configuration/drupal/field.storage.paragraph.field_quotation.yml
configuration/drupal/paragraphs.paragraphs_type.quotation.yml
web/themes/custom/mungo/assets_src/sass/_colors.scss
web/themes/custom/mungo/assets_src/sass/components/paragraph-quote.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/templates/paragraphs/paragraph--quotation.html.twig

DDSDK-20
extra small
Screenshots fra breakpoints
small
large

Quote paragraph

---

web/themes/custom/mungo/assets_src/sass/layout/footer.scss
web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss
web/themes/custom/mungo/templates/block/block--contact.html.twig
web/themes/custom/mungo/templates/layout/page.html.twig
web/themes/custom/mungo/templates/navigation/menu--footer-social.html.twig
web/themes/custom/mungo/templates/navigation/menu--footer.html.twig

DDSDK-69: Theming footer to appear according to design

---

configuration/drupal/core.entity_form_display.paragraph.gallery.default.yml
configuration/drupal/core.entity_view_display.paragraph.gallery.default.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.paragraph.gallery.field_gallery_image.yml
configuration/drupal/field.storage.paragraph.field_gallery_image.yml
configuration/drupal/paragraphs.paragraphs_type.gallery.yml
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/paragraphs/paragraph--gallery.html.twig

Backend setup of the gallery paragraph type

---

web/themes/custom/mungo/assets_src/sass/components/content-link.scss

See Also as a tags should be block-elements

---

web/themes/custom/mungo/assets_src/sass/components/author-presentation.scss
web/themes/custom/mungo/assets_src/sass/components/factbox.scss
web/themes/custom/mungo/assets_src/sass/components/main-media.scss
web/themes/custom/mungo/assets_src/sass/components/paragraph-quote.scss
web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/templates/content/node--article--full.html.twig

Breakpoint cleanup large -> medium

---

configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.event.default.yml
configuration/drupal/field.field.node.event.field_course_id.yml
configuration/drupal/field.field.node.event.field_event_end.yml
configuration/drupal/field.field.node.event.field_event_location_name.yml
configuration/drupal/field.field.node.event.field_event_signup_instructions.yml
configuration/drupal/field.field.node.event.field_event_start.yml
configuration/drupal/field.field.node.event.field_paragraphs.yml
configuration/drupal/node.type.event.yml
web/modules/custom/dds_event/dds_event.info.yml
web/modules/custom/dds_event/src/EventSubscriber/DdsEventAddressFormatSubscriber.php
web/themes/custom/mungo/assets_src/sass/components/box.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--event--full.html.twig
web/themes/custom/mungo/templates/layout/article-layout.twig

Adding boxes to article sidebar and content sidebar

---

composer.lock
web/web.config

Address: 8.1.0-rc1 -> 8.1.0-rc2
Coder: 8.2.8 -> 8.2.9
Console: 1.0.0-beta5 -> 1.0.0-rc5
Core: 8.2.0-rc1 -> 8.2.0
D8 Editor Advanced link: 8.1.2 -> 8.1.3
DDSDK-140

Upgrades DDSDK-140

---

.platform.app.yaml
.platform/services.yaml
composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/search_api.index.nodes.yml
configuration/drupal/search_api.server.solr.yml
configuration/drupal/search_api.settings.yml
configuration/drupal/search_api_solr.settings.yml
configuration/drupal/search_api_solr.standard_highlighter.yml
docker-compose.yml
docker/docker.settings.php
web/sites/default/settings.platformsh.php

Solr setup

---

composer.lock
configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.event.teaser.yml
configuration/drupal/core.extension.yml
configuration/drupal/facets.facet.area.yml
configuration/drupal/facets.facet.event_type.yml
configuration/drupal/facets.facet.target_group.yml
configuration/drupal/facets.facet_source.views_page__events__events_overview.yml
configuration/drupal/field.field.node.event.field_event_area.yml
configuration/drupal/field.storage.node.field_event_area.yml
configuration/drupal/search_api.index.nodes.yml
configuration/drupal/taxonomy.vocabulary.event_location_area.yml
configuration/drupal/views.view.events.yml
web/modules/custom/facets_views_block/facets_views_block.info.yml
web/modules/custom/facets_views_block/facets_views_block.module
web/modules/custom/facets_views_block/templates/facets_views_block-facet.html.twig
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/views/views-view--events--events-overview.html.twig

Facet and event overview setup

---

configuration/drupal/core.date_format.default_time.yml
configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/core.entity_form_display.paragraph.program.default.yml
configuration/drupal/core.entity_form_display.paragraph.program_item.default.yml
configuration/drupal/core.entity_view_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.event.teaser.yml
configuration/drupal/core.entity_view_display.paragraph.program.default.yml
configuration/drupal/core.entity_view_display.paragraph.program_item.default.yml
configuration/drupal/field.field.node.event.field_programs.yml
configuration/drupal/field.field.paragraph.program.field_program_items.yml
configuration/drupal/field.field.paragraph.program.field_program_title.yml
configuration/drupal/field.field.paragraph.program_item.field_program_description.yml
configuration/drupal/field.field.paragraph.program_item.field_program_item_date.yml
configuration/drupal/field.field.paragraph.program_item.field_program_text.yml
configuration/drupal/field.storage.node.field_programs.yml
configuration/drupal/field.storage.paragraph.field_program_description.yml
configuration/drupal/field.storage.paragraph.field_program_item_date.yml
configuration/drupal/field.storage.paragraph.field_program_items.yml
configuration/drupal/field.storage.paragraph.field_program_text.yml
configuration/drupal/field.storage.paragraph.field_program_title.yml
configuration/drupal/paragraphs.paragraphs_type.program.yml
configuration/drupal/paragraphs.paragraphs_type.program_item.yml
web/themes/custom/mungo/assets_src/js/custom/program.js
web/themes/custom/mungo/assets_src/sass/components/program.scss
web/themes/custom/mungo/assets_src/sass/layout/header.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.libraries.yml
web/themes/custom/mungo/templates/paragraphs/paragraph--program.html.twig
web/themes/custom/mungo/templates/paragraphs/paragraph--program_item.html.twig

Program paragraphs for event content type

---

web/themes/custom/mungo/mungo.theme

Format date contional on if the event i an all day event

---

web/themes/custom/mungo/assets_src/sass/layout/footer.scss

Fix padding between footer elements

---

configuration/drupal/core.entity_form_display.paragraph.block.default.yml
configuration/drupal/core.entity_view_display.paragraph.block.default.yml
configuration/drupal/field.field.paragraph.block.field_block.yml
configuration/drupal/field.storage.paragraph.field_block.yml
configuration/drupal/paragraphs.paragraphs_type.block.yml

Adding a block paragraph-type

---

web/themes/custom/mungo/assets_src/js/custom/dropdownmenu.js
web/themes/custom/mungo/assets_src/sass/base/reset.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss

Fixing up menu and search JS

---

configuration/drupal/core.entity_form_display.paragraph.hero_banner.default.yml
configuration/drupal/core.entity_view_display.paragraph.hero_banner.default.yml
configuration/drupal/field.field.node.section_page.field_section.yml
configuration/drupal/field.field.paragraph.hero_banner.field_background_image.yml
configuration/drupal/field.field.paragraph.hero_banner.field_deck_color.yml
configuration/drupal/field.storage.paragraph.field_deck_color.yml
configuration/drupal/responsive_image.styles.wide.yml
web/themes/custom/mungo/assets_src/js/custom/base.js
web/themes/custom/mungo/assets_src/sass/base/media.scss
web/themes/custom/mungo/assets_src/sass/components/hero-banner.scss
web/themes/custom/mungo/assets_src/sass/mixins/buttons.mixins.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/assets_src/sass/theme/backgrounds.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/field/field--node--field-section--section-page.html.twig
web/themes/custom/mungo/templates/paragraphs/paragraph--hero-banner.html.twig

Theming herobanner

---

web/themes/custom/mungo/assets_src/js/custom/exposedFilters.js
web/themes/custom/mungo/assets_src/sass/_colors.scss
web/themes/custom/mungo/assets_src/sass/_variables.scss
web/themes/custom/mungo/assets_src/sass/base/reset.scss
web/themes/custom/mungo/assets_src/sass/base/typography.scss
web/themes/custom/mungo/assets_src/sass/components/facets.scss
web/themes/custom/mungo/assets_src/sass/drupal/forms.scss
web/themes/custom/mungo/assets_src/sass/layout/events.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.info.yml
web/themes/custom/mungo/mungo.libraries.yml
web/themes/custom/mungo/templates/views/views-view--events--events-overview.html.twig

Event filters theming

---

composer.json
composer.lock

Upgrade of all packages and added admin-toolbar

---

web/themes/custom/mungo/assets_src/sass/components/paragraph-quote.scss
web/themes/custom/mungo/assets_src/sass/components/paragraph.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss

Add general spacing between paragraphs

---

web/themes/custom/mungo/assets_src/sass/base/reset.scss
web/themes/custom/mungo/assets_src/sass/base/wysiwyg.scss
web/themes/custom/mungo/assets_src/sass/components/paragraph-text.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss

Lists in text vs floating elements

---

configuration/drupal/block.block.contentgrouping.yml
configuration/drupal/language.content_settings.node.page.yml
configuration/drupal/language.content_settings.node.section_page.yml
configuration/drupal/node.type.page.yml
configuration/drupal/system.menu.content-grouping.yml
web/themes/custom/mungo/assets_src/js/custom/grouping-menu.js
web/themes/custom/mungo/assets_src/sass/_variables.scss
web/themes/custom/mungo/assets_src/sass/components/grouping-menu.scss
web/themes/custom/mungo/assets_src/sass/components/main-media.scss
web/themes/custom/mungo/assets_src/sass/mixins/breakpoints.mixins.scss
web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.libraries.yml
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--section-page--full.html.twig
web/themes/custom/mungo/templates/layout/paragraph--deck.html.twig
web/themes/custom/mungo/templates/navigation/menu--content-grouping.html.twig

Grouping menu

---

configuration/drupal/core.entity_view_display.node.event.search_index.yml
configuration/drupal/field.field.node.event.field_event_end.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col3.yml
configuration/drupal/views.view.events.yml
web/themes/custom/mungo/assets_src/sass/_colors.scss
web/themes/custom/mungo/assets_src/sass/components/event.scss
web/themes/custom/mungo/assets_src/sass/components/facets.scss
web/themes/custom/mungo/assets_src/sass/components/search-result.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--event--search-index.html.twig
web/themes/custom/mungo/templates/layout/search-result.twig

Theme event teasers on search result

---

configuration/drupal/core.base_field_override.node.activity.promote.yml
configuration/drupal/core.entity_form_display.node.activity.default.yml
configuration/drupal/core.entity_view_display.node.activity.default.yml
configuration/drupal/core.entity_view_display.node.activity.teaser.yml
configuration/drupal/field.field.node.activity.field_activity_id.yml
configuration/drupal/field.field.node.activity.field_main_media.yml
configuration/drupal/field.field.node.activity.field_subtitle.yml
configuration/drupal/field.storage.node.field_activity_id.yml
configuration/drupal/language.content_settings.node.activity.yml
configuration/drupal/node.type.activity.yml

Adding an activity content type

---

web/themes/custom/mungo/assets_src/sass/components/search-result.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--event--search-index.html.twig

- make teaser a link
- remove whitespace before colons on labels
- dont show fields that doesnt have values
- fix bug regarding dates that only shows todays date
DDSDK-104

Make teaser a link

---

web/modules/custom/dds_top_image/templates/dds-top-image.html.twig

Add wrapper class that was omitted

---

composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/language.negotiation.yml
configuration/drupal/mungo.settings.yml
configuration/drupal/system.site.yml
configuration/drupal/views.view.badges.yml
web/modules/custom/dds_badge/dds_badge.module
web/modules/custom/dds_top_image/dds_top_image.module
web/themes/custom/mungo/assets_src/sass/components/grouping-menu.scss
web/themes/custom/mungo/assets_src/sass/components/large-button-menu.scss
web/themes/custom/mungo/assets_src/sass/layout/badge-overview.scss
web/themes/custom/mungo/assets_src/sass/mixins/buttons.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/navigation/bef-links--view-badges-overview--maalgruppe.html.twig
web/themes/custom/mungo/templates/navigation/bef-links--view-badges-overview--type.html.twig
web/themes/custom/mungo/templates/views/views-view--badges.html.twig
web/themes/custom/mungo/templates/views/views-view-unformatted--badges.html.twig
web/themes/custom/mungo/theme-settings.php

Badge overview

---

configuration/drupal/block_content.type.article_list.yml
configuration/drupal/core.entity_form_display.block_content.article_list.default.yml
configuration/drupal/core.entity_form_display.node.article.default.yml
configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.block_content.article_list.default.yml
configuration/drupal/core.entity_view_display.node.article.default.yml
configuration/drupal/core.entity_view_display.node.article.rss.yml
configuration/drupal/core.entity_view_display.node.article.teaser.yml
configuration/drupal/core.entity_view_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.node.badge.teaser.yml
configuration/drupal/field.field.block_content.article_list.body.yml
configuration/drupal/field.field.node.article.field_sidedeck.yml
configuration/drupal/field.field.node.badge.field_sidedeck.yml
configuration/drupal/field.field.paragraph.block.field_block.yml
configuration/drupal/field.storage.node.field_sidedeck.yml
configuration/drupal/language.content_settings.block_content.article_list.yml
configuration/drupal/language.negotiation.yml
web/themes/custom/mungo/templates/content/node--article--full.html.twig
web/themes/custom/mungo/templates/content/node--badge--full.html.twig

Add sidedeck to article and badge content types

---

web/themes/custom/mungo/mungo.theme

Support video thumbnails for content-links

---

configuration/drupal/views.view.events.yml
web/modules/custom/dds_event/dds_event.module

Sort events by start date and add a default date filter value

---

configuration/drupal/core.date_format.event_date_long.yml
configuration/drupal/core.date_format.event_date_only.yml
configuration/drupal/core.date_format.event_date_time_long.yml
configuration/drupal/core.date_format.event_date_year_long.yml
web/themes/custom/mungo/templates/content/node--event--search-index.html.twig

Add date formats for localization and display time on day events

---

web/modules/custom/dds_badge/dds_badge.module
web/themes/custom/mungo/assets_src/sass/components/large-button-menu.scss
web/themes/custom/mungo/assets_src/sass/layout/badge-overview.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--badge--full.html.twig

Badge level menu

---

configuration/drupal/core.entity_form_display.paragraph.image.default.yml
configuration/drupal/core.entity_view_display.paragraph.image.default.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.node.badge.field_paragraphs.yml
configuration/drupal/field.field.node.event.field_paragraphs.yml
configuration/drupal/field.field.paragraph.image.field_media_image.yml
configuration/drupal/field.storage.paragraph.field_media_image.yml
configuration/drupal/paragraphs.paragraphs_type.image.yml
web/themes/custom/mungo/mungo.theme

Image paragraph type

---

web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/mungo.theme

Using correct heading size for four and three columns.

---

web/themes/custom/mungo/assets_src/sass/components/paragraph.scss
web/themes/custom/mungo/templates/layout/paragraph--deck.html.twig

Address cols on multiple lines

---

configuration/drupal/core.entity_form_display.paragraph.content_article_reference_ext.default.yml
configuration/drupal/core.entity_view_display.node.article.extended_teaser.yml
configuration/drupal/core.entity_view_display.paragraph.content_article_reference_ext.default.yml
configuration/drupal/core.entity_view_mode.node.extended_teaser.yml
configuration/drupal/field.field.paragraph.1col_deck.field_1col_deck_col1.yml
configuration/drupal/field.field.paragraph.content_article_reference_ext.field_content_reference.yml
configuration/drupal/paragraphs.paragraphs_type.content_article_reference_ext.yml
web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/templates/content/node--extended-teaser.html.twig

Adding extended teaser for 1 col purpose.

---

configuration/drupal/core.entity_form_display.node.download.default.yml
configuration/drupal/core.entity_view_display.node.download.default.yml
configuration/drupal/core.entity_view_display.node.download.teaser.yml
configuration/drupal/field.field.node.download.field_file.yml
configuration/drupal/field.storage.node.field_file.yml
configuration/drupal/language.content_settings.node.download.yml
configuration/drupal/node.type.download.yml
web/themes/custom/mungo/templates/content/node--download--full.html.twig

Add download content type with view mode for showing full node view

---

configuration/drupal/block.block.mungo_branding.yml
configuration/drupal/block.block.mungo_main_menu.yml
configuration/drupal/block.block.mungo_search.yml
web/themes/custom/mungo/assets_src/sass/components/menu.scss
web/themes/custom/mungo/assets_src/sass/layout/header.scss
web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss

.. and add magical values for padding-top for content
DDSDK-160

Remove fixed height of top menu

---

.scrutinizer.yml
configuration/drupal/block.block.contentgrouping.yml
configuration/drupal/block.block.mungo_content.yml
configuration/drupal/block.block.mungo_help.yml
configuration/drupal/block.block.mungo_local_tasks.yml
configuration/drupal/block.block.mungo_page_title.yml
configuration/drupal/core.date_format.event_date_long_time.yml
configuration/drupal/core.entity_view_display.node.activity.default.yml
configuration/drupal/core.extension.yml
configuration/drupal/field.field.node.activity.field_activity_id.yml
configuration/drupal/language/da/core.date_format.long.yml
configuration/drupal/language/da/core.date_format.medium.yml
configuration/drupal/language/da/core.date_format.short.yml
web/modules/custom/dds_activity/dds_activity.info.yml
web/modules/custom/dds_activity/dds_activity.module
web/modules/custom/dds_activity/dds_activity.services.yml
web/modules/custom/dds_activity/src/ActivityFetcher.php
web/modules/custom/dds_activity/src/ClientFactory.php

Fetch activity info on save

---

configuration/drupal/core.extension.yml
configuration/drupal/views.view.events.yml
configuration/drupal/views.view.latest_articles.yml
configuration/drupal/views.view.search.yml
web/modules/custom/dds_search/dds_search.info.yml
web/modules/custom/dds_search/dds_search.module
web/modules/custom/facets_views_block/facets_views_block.module
web/themes/custom/mungo/assets_src/sass/components/paragraph.scss
web/themes/custom/mungo/assets_src/sass/components/search-pager.scss
web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/assets_src/sass/layout/layout.scss
web/themes/custom/mungo/assets_src/sass/layout/view-page.scss
web/themes/custom/mungo/assets_src/sass/mixins/buttons.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/navigation/pager.html.twig
web/themes/custom/mungo/templates/views/views-view--search--content-list.html.twig
web/themes/custom/mungo/templates/views/views-view-unformatted--default--content-list.html.twig

Search result page

---

web/themes/custom/mungo/assets_src/sass/mixins/buttons.mixins.scss

Adjusting buttons

---

web/themes/custom/mungo/assets_src/sass/base/media.scss
web/themes/custom/mungo/templates/content/node--section-page--full.html.twig

Adjusting banner to right size

---

web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/templates/content/node--teaser.html.twig

Render a no-image image when no image :)

---

web/modules/custom/dds_search/dds_search.module

Free-text search should not reset facets

---

web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/paragraphs/paragraph--situation-links--default.html.twig

Links situation boxes

---

web/themes/custom/mungo/assets_src/sass/components/block-local-tasks.scss
web/themes/custom/mungo/assets_src/sass/layout/header.scss

Adjusting menus

---

configuration/drupal/core.entity_form_display.paragraph.1col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.2col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.3col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.4col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.1col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.2col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.3col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.4col_deck.default.yml
configuration/drupal/field.field.paragraph.1col_deck.field_deck_color.yml
configuration/drupal/field.field.paragraph.1col_deck.field_deck_link.yml
configuration/drupal/field.field.paragraph.1col_deck.field_deck_title.yml
configuration/drupal/field.field.paragraph.2col_deck.field_deck_color.yml
configuration/drupal/field.field.paragraph.2col_deck.field_deck_link.yml
configuration/drupal/field.field.paragraph.2col_deck.field_deck_title.yml
configuration/drupal/field.field.paragraph.3col_deck.field_deck_color.yml
configuration/drupal/field.field.paragraph.3col_deck.field_deck_link.yml
configuration/drupal/field.field.paragraph.3col_deck.field_deck_title.yml
configuration/drupal/field.field.paragraph.4col_deck.field_deck_color.yml
configuration/drupal/field.field.paragraph.4col_deck.field_deck_link.yml
configuration/drupal/field.field.paragraph.4col_deck.field_deck_title.yml
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/field/field--paragraph--deckcolumn.html.twig
web/themes/custom/mungo/templates/field/field--paragraph--field-content-reference.html.twig
web/themes/custom/mungo/templates/layout/paragraph--deck.html.twig
web/themes/custom/mungo/templates/paragraphs/paragraph--content-reference.html.twig

Enable column decks to use flexbox equal height

---

web/themes/custom/mungo/templates/content/node--event--search-index.html.twig

Show end time if event is on same day

---

web/themes/custom/mungo/assets_src/sass/components/badge.scss

Add theming of multiple target groups

---

configuration/drupal/core.entity_view_display.node.article.default.yml
configuration/drupal/core.entity_view_display.node.article.extended_teaser.yml
configuration/drupal/core.entity_view_display.node.article.list_teaser.yml
configuration/drupal/core.entity_view_display.node.article.rss.yml
configuration/drupal/core.entity_view_display.node.article.teaser.yml
configuration/drupal/core.entity_view_display.taxonomy_term.content_topic.plaintext.yml
configuration/drupal/core.entity_view_mode.taxonomy_term.plaintext.yml
web/themes/custom/mungo/assets_src/sass/base/typography.scss
web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/assets_src/sass/layout/header.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--article--full.html.twig
web/themes/custom/mungo/templates/content/node--extended-teaser.html.twig
web/themes/custom/mungo/templates/content/node--list-teaser.html.twig
web/themes/custom/mungo/templates/content/node--teaser.html.twig
web/themes/custom/mungo/templates/content/taxonomy-term--plaintext.html.twig
web/themes/custom/mungo/templates/layout/article-layout.twig

Add keyword labels to article teaseres and node view

---

web/themes/custom/mungo/assets_src/sass/components/box.scss
web/themes/custom/mungo/assets_src/sass/components/event.scss
web/themes/custom/mungo/assets_src/sass/layout/events.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/templates/content/node--event--full.html.twig

I have added additonal theming to make it fit the design a little better
DDSDK-179

Add spacing between field elements on events

---

web/themes/custom/mungo/assets_src/sass/components/situation-links.scss
web/themes/custom/mungo/assets_src/sass/layout/article.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss

Adjust headings used.

---

web/modules/custom/dds_activity/src/ActivityFetcher.php
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--teaser.html.twig

Link activity-teaseres to aktdb

---

web/themes/custom/mungo/assets_src/sass/layout/layout.scss
web/themes/custom/mungo/templates/content/node--list-teaser.html.twig
web/themes/custom/mungo/templates/content/node--teaser.html.twig
web/themes/custom/mungo/templates/field/field--paragraph--list-deck.html.twig
web/themes/custom/mungo/templates/layout/paragraph--deck.html.twig
web/themes/custom/mungo/templates/paragraphs/paragraph--latest-content-list.html.twig
web/themes/custom/mungo/templates/views/views-view--default--content-list.html.twig

Fix equal height in Safari

---

composer.json

Patch the chosen module to support required multiple fields

---

configuration/drupal/core.entity_view_display.node.badge.default.yml

Change view mode setting to label

---

configuration/drupal/core.entity_form_display.node.section_page.default.yml
configuration/drupal/core.entity_view_display.node.section_page.default.yml
configuration/drupal/core.entity_view_display.node.section_page.teaser.yml
configuration/drupal/field.field.node.section_page.field_content_category.yml
configuration/drupal/field.field.node.section_page.field_content_tag.yml
configuration/drupal/field.field.node.section_page.field_content_target_group.yml
configuration/drupal/field.field.node.section_page.field_content_topic.yml
web/modules/custom/dds_layout/dds_layout.module
web/themes/custom/mungo/templates/content/node--teaser.html.twig

meta-taxonomies on section pages

---

configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.node.badge.teaser.yml
configuration/drupal/field.field.node.badge.field_content_category.yml
configuration/drupal/field.field.node.badge.field_content_tag.yml
configuration/drupal/field.field.node.badge.field_content_topic.yml
configuration/drupal/language/da/facets.facet.target_group.yml
configuration/drupal/language/da/field.storage.node.field_badge_type.yml
configuration/drupal/language/da/system.site.yml
configuration/drupal/system.site.yml
web/themes/custom/mungo/templates/content/node--teaser.html.twig

Meta terms on badges

---

configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_form_display.node.download.default.yml
configuration/drupal/core.entity_view_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.node.badge.teaser.yml
configuration/drupal/core.entity_view_display.node.download.default.yml
configuration/drupal/core.entity_view_display.node.download.list_teaser.yml
configuration/drupal/core.entity_view_display.node.download.teaser.yml
configuration/drupal/core.entity_view_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.section_page.default.yml
configuration/drupal/field.field.node.badge.field_badge_target_group.yml
configuration/drupal/field.field.node.download.field_content_category.yml
configuration/drupal/field.field.node.download.field_content_tag.yml
configuration/drupal/field.field.node.download.field_content_target_group.yml
configuration/drupal/field.field.node.download.field_content_topic.yml
web/modules/custom/dds_layout/dds_layout.module

Adding meta terms to downloads and cleaning the rest up a bit

---

web/themes/custom/mungo/assets_src/sass/layout/layout.scss

Remove propety that messes with the flexbox

---

configuration/drupal/core.entity_view_display.paragraph.1col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.2col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.3col_deck.default.yml
configuration/drupal/core.entity_view_display.paragraph.4col_deck.default.yml

Remove labels for col decks

---

configuration/drupal/facets.facet.content_type.yml
configuration/drupal/views.view.search.yml
web/modules/custom/facets_views_block/facets_views_block.module
web/themes/custom/mungo/templates/views/views-view--search--content-list.html.twig

Add content type facet to searches

---

web/themes/custom/mungo/assets_src/sass/components/facets.scss

Make submits 100% of filter width

---

web/themes/custom/mungo/assets_src/sass/layout/header.scss

Add z-index to search in menu

---

composer.json
composer.lock
web/modules/custom/dds_event/src/EventSubscriber/DdsEventAddressFormatSubscriber.php

Makes it possible to leave out any field, we'd prefer to go to beta2
as soon as possible but it has not yet been released.
DDSDK-91

Bump the addressing library one commit

---

web/themes/custom/mungo/templates/content/node--list-teaser.html.twig

Make activities in list-teasers link to aktdb

---

web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss

Set overflow to unset to fix main menu dropdown

---

web/themes/custom/mungo/assets_src/sass/components/inspiration-deck.scss
web/themes/custom/mungo/assets_src/sass/drupal/views.scss
web/themes/custom/mungo/assets_src/sass/layout/layout.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/templates/views/views-view--badges.html.twig

Fix equal heights

---

web/modules/custom/dds_top_image/templates/dds-top-image.html.twig

Add narrow class to get wanted behaviour of top image

---

web/themes/custom/mungo/assets_src/sass/components/hero-banner.scss

Add fixed width to get equal sies on mobile and tablet

---

web/themes/custom/mungo/assets_src/sass/layout/layout.scss

Paragraphs inside euqual height grids should be 100% in width

---

web/themes/custom/mungo/assets_src/sass/components/paragraph.scss

Fix negative margin

---

configuration/drupal/core.entity_view_display.node.section_page.teaser.yml

Add main image to section page teasers

---

configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col1.yml
configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col2.yml

Adding fields to two-col deck

---

web/themes/custom/mungo/assets_src/sass/components/inspiration-deck.scss

Text left didn't reset properly on resize

---

web/themes/custom/mungo/templates/field/field--paragraph--deckcolumn.html.twig

Adding column classes to two column deck.

---

web/themes/custom/mungo/assets_src/sass/base/typography.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss

Adjusting line height and using mixing instead.

---

web/themes/custom/mungo/mungo.theme

Corrected wrong return-specification

---

composer.json
composer.lock

Fix target-group suppressed validation errors

---

configuration/drupal/core.entity_form_display.node.event.default.yml

Move "Programs" to the bottom of the event-edit form

---

web/modules/custom/dds_badge/dds_badge.module

Make it possible to create progression-badges without progressions

---

composer.lock
configuration/drupal/search_api.server.solr.yml

General upgrade of core and modules

---

composer.json
configuration/drupal/facets.facet.area.yml
configuration/drupal/facets.facet.event_type.yml
configuration/drupal/facets.facet.target_group.yml
docker-compose.yml

Sort facets by term weight

---

web/modules/custom/dds_content_list/dds_content_list.module

Make sure content-list cache-tags bubles to the page

---

web/themes/custom/mungo/assets_src/sass/components/download.scss

restyling download links

---

configuration/drupal/core.entity_form_display.node.activity.default.yml
configuration/drupal/core.entity_view_display.node.activity.default.yml
configuration/drupal/core.entity_view_display.node.activity.teaser.yml
configuration/drupal/field.field.node.activity.field_content_topic.yml
web/themes/custom/mungo/templates/content/node--teaser.html.twig

Add topic to content_type activity

---

web/themes/custom/mungo/templates/content/node--download--list-teaser.html.twig
web/themes/custom/mungo/templates/content/node--download--teaser.html.twig

Click on the download icon should also open a tab

---

web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss

Fix scrollbars that appeared in the menu on IE11

---

web/themes/custom/mungo/assets_src/sass/components/content_list.scss

Fixing IE issue by forcing 100% width

---

web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/views/container--view--latest-articles.html.twig

Remove container that wraps content lists and breaks flexbox

---

configuration/drupal/core.entity_form_display.media.image.20_7.yml
configuration/drupal/core.entity_form_display.media.image.main_media_with_25_6.yml
configuration/drupal/core.entity_form_display.node.section_page.default.yml
configuration/drupal/core.entity_form_display.paragraph.hero_banner.default.yml
configuration/drupal/core.entity_form_mode.media.20_7.yml
configuration/drupal/core.entity_form_mode.media.main_media_with_25_6.yml
configuration/drupal/core.entity_view_display.media.image.20_7.yml
configuration/drupal/core.entity_view_display.media.image.section_main_media_25_6.yml
configuration/drupal/core.entity_view_display.node.section_page.default.yml
configuration/drupal/core.entity_view_display.paragraph.hero_banner.default.yml
configuration/drupal/core.entity_view_mode.media.20_7.yml
configuration/drupal/core.entity_view_mode.media.section_main_media_25_6.yml
configuration/drupal/crop.type.20_7.yml
configuration/drupal/crop.type.25_6.yml
configuration/drupal/image.style.20_7_1600x560.yml
configuration/drupal/image.style.20_7_200x70.yml
configuration/drupal/image.style.25_6_1600x384.yml
configuration/drupal/image.style.25_6_200x48.yml

Section and hero-banner crops

---

web/themes/custom/mungo/assets_src/sass/components/inspiration-deck.scss

Adding a padding to solve Safari issue on inspiration deck

---

web/themes/custom/mungo/assets_src/sass/layout/deck.scss
web/themes/custom/mungo/mungo.theme

Adjusting grid and headings for lists

---

web/themes/custom/mungo/mungo.theme

Adding pre-render specific key to render cache

---

web/themes/custom/mungo/assets_src/sass/components/key_figures.scss
web/themes/custom/mungo/templates/paragraphs/paragraph--key-figures.html.twig

Add margin before and after the key-figures deck

---

configuration/drupal/core.entity_form_display.media.image.original.yml
configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_form_mode.media.original.yml
configuration/drupal/core.entity_view_display.media.image.original.yml
configuration/drupal/core.entity_view_display.node.badge.default.yml
configuration/drupal/core.entity_view_mode.media.original.yml
web/themes/custom/mungo/mungo.theme

Fix images on badge-pages

---

configuration/drupal/core.entity_form_display.node.activity.default.yml

Switch widget for topic

---

configuration/drupal/core.entity_view_display.node.activity.list_teaser.yml
configuration/drupal/core.entity_view_display.node.article.list_teaser.yml
configuration/drupal/core.entity_view_display.node.badge.list_teaser.yml
configuration/drupal/core.entity_view_display.node.event.list_teaser.yml
configuration/drupal/core.entity_view_display.node.section_page.list_teaser.yml
web/themes/custom/mungo/templates/content/node--list-teaser.html.twig

Add meta-label to content in the list-teaser view-mode

---

web/themes/custom/mungo/assets_src/sass/layout/layout.scss

Removing set of width on these elements.

---

configuration/drupal/core.entity_view_display.media.video.extended_teaser.yml

Add extended teaser view-mode for video and reduce thumbnail size

---

web/themes/custom/mungo/assets_src/sass/components/inspiration-deck.scss
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/content/node--list-teaser.html.twig
web/themes/custom/mungo/templates/misc/forward.html.twig
web/themes/custom/mungo/templates/paragraphs/paragraph--inspiration-deck--default.html.twig

Set inspirational foreground

---

web/themes/custom/mungo/assets_src/sass/layout/article.scss

Add spacing from keyword down to content in list teasers

---

composer.json
composer.lock
configuration/drupal/core.entity_view_mode.block.token.yml
configuration/drupal/core.entity_view_mode.block_content.token.yml
configuration/drupal/core.entity_view_mode.contact_message.token.yml
configuration/drupal/core.entity_view_mode.crop.token.yml
configuration/drupal/core.entity_view_mode.file.token.yml
configuration/drupal/core.entity_view_mode.media.token.yml
configuration/drupal/core.entity_view_mode.menu_link_content.token.yml
configuration/drupal/core.entity_view_mode.node.token.yml
configuration/drupal/core.entity_view_mode.paragraph.token.yml
configuration/drupal/core.entity_view_mode.search_api_task.token.yml
configuration/drupal/core.entity_view_mode.shortcut.token.yml
configuration/drupal/core.entity_view_mode.taxonomy_term.token.yml
configuration/drupal/core.entity_view_mode.user.token.yml
configuration/drupal/core.extension.yml
configuration/drupal/language.content_settings.redirect.redirect.yml
configuration/drupal/pathauto.pattern.node_article.yml
configuration/drupal/pathauto.pattern.node_badge.yml
configuration/drupal/pathauto.pattern.node_event.yml
configuration/drupal/pathauto.pattern.node_section_page.yml
configuration/drupal/pathauto.settings.yml
configuration/drupal/redirect.settings.yml
configuration/drupal/system.action.pathauto_update_alias_node.yml
configuration/drupal/system.action.pathauto_update_alias_user.yml
configuration/drupal/system.action.redirect_delete_action.yml
configuration/drupal/views.view.redirect.yml
web/modules/custom/dds_admin/dds_admin.info.yml
web/modules/custom/dds_admin/dds_admin.module
web/themes/custom/mungo/mungo.theme

Setup path-auto and redirect

---

composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/google_analytics.settings.yml
web/sites/default/docker.settings.php
web/sites/default/platformsh.common.settings.php
web/sites/default/platformsh.env.master.settings.php

Setup google analytics and property-ids for envionments

---

configuration/drupal/core.entity_view_display.media.image.extended_teaser.yml
configuration/drupal/core.entity_view_display.media.video.extended_teaser.yml
configuration/drupal/core.entity_view_mode.media.extended_teaser.yml

Extended teaser should be 16:9 and the video should be a player

---

composer.json
composer.lock
configuration/drupal/core.entity_view_display.paragraph.gallery.default.yml
web/themes/custom/mungo/assets_src/js/custom/gallery.js
web/themes/custom/mungo/assets_src/sass/_variables.scss
web/themes/custom/mungo/assets_src/sass/components/gallery.scss
web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss
web/themes/custom/mungo/assets_src/sass/mixins/typography.mixins.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/mungo.libraries.yml
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/paragraphs/paragraph--gallery.html.twig

Use flexslider2 for the gallery

---

web/themes/custom/mungo/assets_src/js/custom/dropdownmenu.js

Support hover over menus.

---

web/modules/custom/dds_layout/dds_layout.module
web/themes/custom/mungo/mungo.theme

Proper support of 33/66 twocol

---

composer.json
patches/core-language-initialization-8.2.6-reroll-2650434.patch

Had to reroll the patch as the issue is against 8.4
DDSDK-350

Added patch for fixing a language issue

---

web/sites/default/docker.settings.php
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/layout/page.html.twig

Make sizebar configurable

---

web/modules/custom/dds_search/dds_search.module
web/themes/custom/mungo/assets_src/sass/components/search-pager.scss

Reformat dates before rendering pager

---

configuration/drupal/search_api.index.nodes.yml
configuration/drupal/views.view.search.yml

Adding sticky to searchapi and updating search result order

---

web/themes/custom/mungo/theme-settings.php

Remember to register a file-usage for uploaded file

---

configuration/drupal/system.file.yml

We dont have an issue for these fixes

Minor fixes made after go-live

---

composer.json
composer.lock
configuration/drupal/core.extension.yml

Adding dropguard

---

web/themes/custom/mungo/templates/paragraphs/paragraph--inspiration-deck--default.html.twig

Inspiration link-color should not be blue DDSDK-353

---

web/themes/custom/mungo/mungo.theme

Fix date that where formatted as UTC

---

configuration/drupal/core.entity_form_display.node.article.default.yml
configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/core.entity_form_display.node.section_page.default.yml
configuration/drupal/core.entity_form_display.paragraph.1col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.2col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.3col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.4col_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.dynamic_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.list_deck.default.yml
configuration/drupal/core.entity_form_display.paragraph.program.default.yml

Switching all paragraph forms to "collapsed"

---

web/themes/custom/mungo/mungo.theme

Fixing date-format, it should be danish

---

configuration/drupal/core.date_format.event_short_date_no_time.yml
configuration/drupal/language/da/core.date_format.event_short_date_no_time.yml
web/themes/custom/mungo/mungo.theme

Introducing proper date-format and refactoring

---

web/modules/custom/dds_search/src/EventSubscriber/DefaultDateRedirectEventSubscriber.php

Kill cache for redirects

---

web/themes/custom/mungo/assets_src/js/custom/dropdownmenu.js
web/themes/custom/mungo/assets_src/sass/components/menu.scss
web/themes/custom/mungo/assets_src/sass/mixins/menus.mixins.scss

- Fix body while the mobil-menu is open to prevent back-scrolling 
- Introduce a way to disable auto-close-on-scroll
DDSDK-360

A number of fixes to the menu

---

composer.json
composer.lock

Upgrading core from 8.2.7 -> 8.2.8

---

web/modules/custom/dds_admin/dds_admin.module

Fixing broken "paste from word" functionality

---

composer.lock

Upgrading core from 8.3.1 to 8.3.2

---

composer.lock
web/.gitattributes

Upgrading core and dependencies 8.3.2 -> 8.3.4

---

composer.json
composer.lock

Module did not get updated due to version specification combining ~ and
hotfix version.
Updated version needs to be repatched as well.

Update Chosen to 2.4

---

composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/system_status.settings.yml
docker-compose.yml

Security upgrade of core and added the status_update module

---

configuration/drupal/views.view.badges.yml
configuration/drupal/views.view.events.yml

Fix broken metatag configuration

---

composer.json
composer.lock

Patching core to fix broken redirects

---

composer.json
composer.lock
web/sites/example.settings.local.php

See https://www.drupal.org/node/2915430
DDSDK-380

Upgrade core to 8.4.2 mainly to fix redirect/core bug

---

web/modules/custom/facets_views_block/facets_views_block.module

Get translated facet name from configuration

---

web/sites/default/docker.settings.php
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/layout/html.html.twig

Enable hotjar via featureflag

---

configuration/drupal/search_api.index.nodes.yml
configuration/drupal/views.view.events.yml
configuration/drupal/views.view.search.yml

Switch tags to full-text and change event and general search order

---

configuration/drupal/facets.facet.topic_taxonomy_term_name.yml

Adding term facet

---

composer.json
composer.lock
configuration/drupal/core.entity_form_display.node.article.default.yml
configuration/drupal/core.entity_form_display.node.badge.default.yml
configuration/drupal/core.entity_form_display.node.download.default.yml
configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/core.entity_form_display.node.section_page.default.yml
configuration/drupal/core.entity_view_display.node.article.default.yml
configuration/drupal/core.entity_view_display.node.badge.default.yml
configuration/drupal/core.entity_view_display.node.download.default.yml
configuration/drupal/core.entity_view_display.node.event.default.yml
configuration/drupal/core.entity_view_display.node.section_page.default.yml
configuration/drupal/core.extension.yml
configuration/drupal/field.field.node.article.field_exclude_from_search.yml
configuration/drupal/field.field.node.badge.field_exclude_from_search.yml
configuration/drupal/field.field.node.download.field_exclude_from_search.yml
configuration/drupal/field.field.node.event.field_exclude_from_search.yml
configuration/drupal/field.field.node.section_page.field_exclude_from_search.yml
configuration/drupal/field.storage.node.field_exclude_from_search.yml
configuration/drupal/search_api.index.nodes.yml

Add search_api_exclude_entity

---

configuration/drupal/views.view.search.yml

Hide past events in the general search

---

configuration/drupal/core.entity_form_display.paragraph.markup.default.yml
configuration/drupal/core.entity_view_display.paragraph.markup.default.yml
configuration/drupal/core.entity_view_display.paragraph.markup.search_index.yml
configuration/drupal/field.field.node.article.field_paragraphs.yml
configuration/drupal/field.field.node.badge.field_paragraphs.yml
configuration/drupal/field.field.node.event.field_paragraphs.yml
configuration/drupal/field.field.paragraph.1col_deck.field_1col_deck_col1.yml
configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col1.yml
configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col2.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col1.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col2.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col3.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col1.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col2.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col3.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col4.yml
configuration/drupal/field.field.paragraph.dynamic_deck.field_paragraphs.yml
configuration/drupal/field.field.paragraph.markup.field_markup.yml
configuration/drupal/field.storage.paragraph.field_markup.yml
configuration/drupal/paragraphs.paragraphs_type.markup.yml

This is the first step towards switching our "full html" text-filter over to be more filtered.
DDSDK-381

Introduce a markup paragraph type and use it where we allow text

---

docker-compose.yml

The old ddsdk image has been removed and the new taken it's place.

Update db dump

---

configuration/drupal/editor.editor.full_html.yml
configuration/drupal/filter.format.full_html.yml

Enable filtering, allow b tags for now

---

configuration/drupal/views.view.badges.yml
web/modules/custom/dds_badge/dds_badge.install

- /maerker renamed /maerker-gamle
- /maerker-2018 renamed to /maerker
- add redirect from /maerker-2018 to /maerker
See DDSDK-415.

Rename paths form Mærker

---

configuration/drupal/mungo.settings.yml

Update badge description text

---

configuration/drupal/mungo.settings.yml
configuration/drupal/views.view.badges.yml
docker-compose.yml
docker/init/ZZZ-finished-init.sh
web/modules/custom/dds_badge/dds_badge.module
web/modules/custom/dds_metatag/dds_metatag.module
web/modules/custom/dds_update/dds_update.install
web/themes/custom/mungo/theme-settings.php

Titel og beskrivelse skal kunne være forskellig på nye og gamle mærker-view

---

web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/paragraphs/paragraph--content-link.html.twig

Content links to download content should link to the file

---

.platform.app.yaml

See https://docs.platform.sh/configuration/routes/https.html#automatic-certificate-renewal

Make sure Platform.sh uses a renewed certificate

---

.gitignore
README.md
docker-compose-dev.yml
docker-compose.yml
scripts/docker/_docker-common.sh
scripts/docker/docker-reset.sh

Upgrade docker-compose and reset setup

---

configuration/drupal/forward.settings.yml
configuration/drupal/language/da/forward.settings.yml

Added missing forward configuration that resulted in a notice.

---

configuration/drupal/views.view.jobpostings.yml
web/themes/custom/mungo/assets_src/sass/components/jobpostings.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss

DDSDK-431
Before (https://dds.dk/job):
After (https://feature-ddsdk-431-job-yqpin3q-55isd6w54kg6s.eu.platform.sh/job):

Style individual jobpostings to add a bit more spacing

---

.platform.app.yaml
composer.lock
configuration/drupal/block.block.contentgrouping.yml
configuration/drupal/block.block.footer.yml
configuration/drupal/block.block.footersocial.yml
configuration/drupal/block.block.mungo_account_menu.yml
configuration/drupal/block.block.mungo_footer.yml
configuration/drupal/block.block.mungo_main_menu.yml
configuration/drupal/block.block.topmenu.yml
configuration/drupal/core.entity_form_display.node.event.default.yml
configuration/drupal/field.field.node.event.field_event_address.yml
configuration/drupal/taxonomy.vocabulary.badge_target_group.yml
configuration/drupal/taxonomy.vocabulary.content_category.yml
configuration/drupal/taxonomy.vocabulary.content_tag.yml
configuration/drupal/taxonomy.vocabulary.content_target_group.yml
configuration/drupal/taxonomy.vocabulary.content_topic.yml
configuration/drupal/taxonomy.vocabulary.event_location_area.yml
configuration/drupal/taxonomy.vocabulary.event_type.yml
configuration/drupal/taxonomy.vocabulary.person.yml
configuration/drupal/taxonomy.vocabulary.progression_badge.yml
docker-compose.yml
package.json
scripts/docker/_docker-common.sh
scripts/docker/site-reset.sh
web/modules/custom/dds_badge/dds_badge.module
web/modules/custom/dds_layout/dds_layout.module
web/sites/default/default.settings.php
web/themes/custom/mungo/mungo.theme

Opdatering af moduler og core.
PHP opdateres fra PHP 7.0 til PHP 7.2

Core and module updates, etc.

---

composer.json
composer.lock
docker-compose.yml

Also since we are now on Drush 9 specify Drush URI option in docker setup.

Update Drush to version 9

---

web/themes/custom/mungo/mungo.theme

Kan testes på https://pr-321-nkazswa-55isd6w54kg6s.eu.platform.sh/artikel/korpsledelsen
See DDSDK-332.

Add destination parameter to mail link URLs

---

configuration/drupal/core.entity_form_display.paragraph.content_section_reference.default.yml
configuration/drupal/core.entity_view_display.node.event.extended_teaser.yml
configuration/drupal/core.entity_view_display.node.section_page.extended_teaser.yml
configuration/drupal/core.entity_view_display.paragraph.content_section_reference.default.yml
configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col1.yml
configuration/drupal/field.field.paragraph.2col_deck.field_2col_deck_col2.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col1.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col2.yml
configuration/drupal/field.field.paragraph.3col_deck.field_3col_deck_col3.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col1.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col2.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col3.yml
configuration/drupal/field.field.paragraph.4col_deck.field_4col_deck_col4.yml
configuration/drupal/field.field.paragraph.content_section_reference.field_content_reference.yml
configuration/drupal/paragraphs.paragraphs_type.content_article_reference_ext.yml
configuration/drupal/paragraphs.paragraphs_type.content_section_reference.yml
web/themes/custom/mungo/templates/content/node--extended-teaser.html.twig

Reference extended paragraph includes  section + events.

---

.github/main.workflow
.github/workflows/push.yml

Se bort fra det fejlende CircleCI check. Der er ikke konfigureret noget CircleCI på denne branch eller på master. Grunden til det kører er fordi det er ved at blive tilføjet i #341.

Migrate to GitHub Actions v2

---

composer.lock

Contrib module updates. DDSDK-442

---

composer.json
composer.lock
configuration/drupal/core.extension.yml
configuration/drupal/file.settings.yml
configuration/drupal/system.file.yml
configuration/drupal/views.view.files.yml
web/modules/custom/dds_admin/dds_admin.module
web/modules/custom/dds_update/dds_update.install

Mark unused files as temporary
n/a
n/a
Builds on top of #348. So focusing on the last two commits should be sufficient.
DDSDK-450.
n/a
n/a

Mark unused files as temporary

---

README.md

Running entity-update was remove some versions ago

---

README.md
docker-compose.mac-nfs.yml
docker-compose.yml
scripts/docker/docker-reset.sh
scripts/docker/site-reset.sh

- Tweak the docker files to support Mac NFS 
- Fix the startup script
- Update the documentation
There's still plenty of space for improvement, but this is the amount I want to open pandoras box today :)
I've tested the NFS setup locally and it appears to work. Hoozah!

Replace docker-sync with NFS for mac.

---

.platform.app.yaml
web/themes/custom/mungo/assets_src/sass/components/activity.scss

Fixes issue with space between gallery and footer on activity page
Checkout difference between:
Live: https://dds.dk/aktivitet/abc-klippekort
Test environment: https://pr-363-mee7dki-55isd6w54kg6s.eu.platform.sh/aktivitet/abc-klippekort

Fixes issue with space between gallery and footer on activity page

---

.platform.app.yaml

Use drush in vendor dir

---

.environment
.platform.app.yaml

Use environment file to include vendor in path

---

composer.json
composer.lock
docker-compose.yml

Update Drupal core to 8.9.14.
Add `COMPOSER_MEMORY_LIMIT=-1` to docker environments. Otherwise I couldn't run composer.
n/a
n/a
n/a
See DDSDK-491.
n/a
n/a

Update Drupal core to 8.9.14

---

.github/workflows/push.yml
.github/workflows/visual-test.yml

This does a few changes which aims to simplify our GH Actions setup.

Clean up GH Actions.

---

docker-compose.yml

Make xdebug V3 work.

---

configuration/drupal/monitoring.sensor_config.disk_usage.yml
configuration/drupal/search_api.index.nodes.yml
configuration/drupal/search_api.server.solr.yml
docker-compose.yml
package-lock.json
web/sites/default/docker.settings.php

- Config export to bring git in sync with actual config
- Add support for ddsdk.local as dev domain
- Update package-lock.json
- Increase limit for disk alerts
n/a
n/a
n/a
n/a
n/a
n/a

Misc tweaks

---

web/themes/custom/mungo/assets_src/sass/components/inspiration-deck.scss

Fix flexbox issue in Chrome + Edge

---

web/themes/custom/mungo/mungo.theme

Fix deprecated service. DDSDK-499

---

configuration/drupal/language/da/user.mail.yml
configuration/drupal/language/da/views.view.block_content.yml
configuration/drupal/language/da/views.view.frontpage.yml
configuration/drupal/language/da/views.view.media.yml
configuration/drupal/language/en/node.type.article.yml
configuration/drupal/node.type.article.yml
configuration/drupal/node.type.redirect_page.yml
configuration/drupal/taxonomy.vocabulary.activity_type.yml

Export missing config after D9 upgrade.

---

web/sites/default/platformsh.env.master.settings.php
web/themes/custom/mungo/mungo.theme
web/themes/custom/mungo/templates/layout/html.html.twig

DDS has a new linkedIN tracking script.
I've made sure that it's only loaded on the master/prod environment.
This will need to be updated with `text/plain` when the Cookiebot compliance script is added :)

DDSDK-518 - LinkedIN script.

---

web/modules/custom/dds_tracking/dds_tracking.module
web/modules/custom/dds_tracking/templates/dds_tracking_info_box.html.twig
web/themes/custom/mungo/assets_src/sass/components/markup.scss
web/themes/custom/mungo/assets_src/sass/drupal/cookieconsent.scss
web/themes/custom/mungo/assets_src/sass/mungo.bundle.scss
web/themes/custom/mungo/templates/layout/html.html.twig

DDSDK-531
It makes LInkedIn compliant
It runs through iframes and scrip tags in the markup field and tries to match them to known providers. Then makes them compliant in accordance.
Youtube: https://pr-390-7xtyelq-55isd6w54kg6s.eu.platform.sh/artikel/morgenmaden-sikrer-en-god-start-paa-dagen
Isuue: https://pr-390-7xtyelq-55isd6w54kg6s.eu.platform.sh/artikel/hent-aktivitetsmateriale-til-spejderdagen-2018
Facebook: https://pr-390-7xtyelq-55isd6w54kg6s.eu.platform.sh/artikel/ny-bliv-leder-kampagne-skudt-i-gang
LinkedIn kan ikke rigtig tests, medmindre man kigger i kildekoden efter `_linkedin_partner_id = "3852801";`

Set linkedin scripts to cookiebot statistics level

---

web/themes/custom/mungo/assets_src/sass/drupal/cookieconsent.scss

Make cookiebot checkboxes clickable

Make cookiebot checkboxes clickable

---

.github/workflows/action-approve-failure.yml
.github/workflows/visual-test.yml

Fix backstop

---

.github/workflows/drupal-security-jira.yml
.github/workflows/github-security-jira.yml

And change security watcher to Trine.
n/a
n/a
The visual diff is due to image not being fully loaded when the snapshots are taken. This is unrelated to the change and a known issue.
RI-122.
n/a
n/a

Enable drupal-security-jira scheduled check

---

composer.json
composer.lock

- composer update drupal/core "drupal/core-*" --with-all-dependencies
- drush updb -y
- drush cex -y

Update core to 9.2.13. SA-CORE-2022-003

---

.platform.app.yaml

Disk-size increase.

---

composer.json
composer.lock

Patches https://www.drupal.org/sa-core-2022-008
1. `composer update drupal/core "drupal/core-*" --with-all-dependencies` 
2. `drush updb -y` 
3. `drush cex`
DDSDK-554

SA-CORE-2022-008: Update Drupal core

---

web/themes/custom/mungo/assets_src/sass/track/_teasers.scss

Fixes the track-star placement on events so that they're placed to their parent

SPJ-155: Place track star relative to it's parent

---

.platform.app.yaml

We can make StatusCake monitor them.

Register result of crons jobs

---

docker-compose.yml

Use new Docker image registries.

Use new Docker image registries

---

.platform.app.yaml

See https://reload.zulipchat.com/#narrow/stream/235451-dev-snak/topic/APC.20caching.20i.20Drupal.209/near/282771999

Add apcu extension

---

configuration/drupal/core.entity_form_display.paragraph.read_more.default.yml
configuration/drupal/core.entity_view_display.paragraph.read_more.default.yml
configuration/drupal/field.field.paragraph.read_more.field_1col_deck_col1.yml
configuration/drupal/field.field.paragraph.read_more.field_title.yml
configuration/drupal/field.storage.paragraph.field_title.yml
web/themes/custom/mungo/templates/field/paragraph--read-more.html.twig

This PR adds  a title field for the "read more" paragraph, so it is possible to change the title of the accordions. 
will default to "læs mere / read more" 
https://reload.atlassian.net/browse/DDSDK-607

Added title field for accordionss

---

.github/workflows/drupal-security-jira.yml
.github/workflows/github-security-jira.yml

Anne is the new Trine while Trine is on maternity leave :)

Use maternity leave substitute for sec. issues

---

web/sites/default/docker.settings.php
web/sites/default/platformsh.env.master.settings.php
web/themes/custom/mungo/mungo.theme

Adds plausible to ddsdk.docker and dds.dk 
Open ddsdk.docker and plausible, see if it works.

Added plausible to local / Prod

---

.platform.app.yaml
.platform/services.yaml
composer.json
composer.lock
configuration/drupal/google_analytics.settings.yml

Bump disk size. + Update Google Analytics

---

.platform.app.yaml
.platform/services.yaml
composer.json
composer.lock
configuration/drupal/forward.settings.yml

Unbump diskspace

---

cypress/e2e/browsing.cy.js
lostpixel.config.js

Add mask, to avoid flaky issues with LostPixel

---

.github/workflows/drupal-security-jira.yml
.github/workflows/github-security-jira.yml

Use an action variable, so future changes won't need a commit and hence a deployment.

New Jira watchers

---

.github/workflows/frontend.yml
.platform.app.yaml
docker-compose.yml

https://pr-486-qd6hpzi-55isd6w54kg6s.eu.platform.sh/
https://nodejs.org/en/about/previous-releases

Upgrade to nodejs v20
